
[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "管理"
  url = "/admin/"
  weight = 30

[[main]]
  name = "文档"
  pageRef = "docs"
  weight = 15

# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 30

[[main]]
  identifier = "github2"
  pre = "github"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 40

[[footer]]
  name = "Privacy"
  url = "https://external-link"